version: "2"

services:
  db:
    build: .
    image: postgres
    environment:
      POSTGRES_DB: precato_db
      POSTGRES_USER: rafael
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./:/app
    ports:
      - "5432:5432"
  web: 
    image: precato-pg-test
    depends_on:
      - db
    ports:
      - "4000:4000"